sudo: required

services:
  - docker

language: python

matrix:
  include:
    - python: 3.6

env:
  - STREAMZ_LAUNCH_KAFKA=true

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda env create --name test-streamz --file ./conda/environments/streamz_dev.yml
  - source activate test-streamz
  - pip install git+https://github.com/dask/distributed.git --upgrade --no-deps

  - python setup.py install

script:
  - coverage run run_tests.py --runslow
  - flake8 streamz

after_success:
  - codecov

notifications:
  email: false
